name: Tests

on:  
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: ‘17’
        distribution: ‘temurin’
        cache: ‘gradle’
    - name: Gradle build
      run: ./gradlew :thrift:buildPlugin
    - name: Run build with Gradle Wrapper
      run: ./gradlew test
